services:
  - type: web
    name: supabase-render
    plan: free
    region: oregon  # Añade región específica
    dockerComposePath: docker/docker-compose.yml
    env: free
    envVars:
      - key: POSTGRES_PASSWORD
        value: P@ssw0rd_S3gur0_2024  # Cambiar por tu contraseña real
      - key: JWT_SECRET
        value: abcDEF123$$%xyz789    # Cambiar por tu secreto real
      - key: SITE_URL
        value: https://supabase-render.onrender.com
      - key: ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c  # Reemplazar con clave válida
      - key: SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c  # Reemplazar con clave válida
    healthCheckPath: /rest/v1/
    autoDeploy: true