services:
  - type: web
    name: supabase-render
    plan: free                # Plan gratuito (o "starter" para DB persistente)
    dockerComposePath: docker/docker-compose.yml  # Ruta al compose
    env: free
    
    # Variables de entorno CRÍTICAS para Supabase
    envVars:
      - key: POSTGRES_PASSWORD
        value: P@ssw0rd_S3gur0_2024  # ¡Cambia esto! Usa una contraseña compleja.
      - key: JWT_SECRET
        value: abcDEF123$$%xyz789     # Mínimo 32 caracteres, ¡cambia esto!
      - key: SITE_URL
        value: https://supabase-render.onrender.com  # Ajusta al nombre de tu servicio
      - key: ANON_KEY
        generateValue: true           # Render generará uno automáticamente
      - key: SERVICE_ROLE_KEY
        generateValue: true           # Render generará uno automáticamente

    # Configuración avanzada (opcional pero recomendada)
    healthCheckPath: /rest/v1/        # Endpoint para health checks
    autoDeploy: true                  # Despliegue automático en cambios